apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: mlflow-deployment
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: mlflow
    spec:
      containers:
      - name: mlflow
        image: ronychatterjee/mlflowsql:latest
        imagePullPolicy: Always
        ports:
        - name: http-port
          containerPort: 5000
---
apiVersion: v1
kind: Service
metadata:
  name: mlflow-svc
spec:
  selector:
    app: mlflow
  type: LoadBalancer
  ports:
  - protocol: TCP
    targetPort: http-port
    port: 5000
